#ifndef BIOXASIMAGINGCARBONFILTERFARM_H
#define BIOXASIMAGINGCARBONFILTERFARM_H

#include "beamline/BioXAS/BioXASCarbonFilterFarm.h"

// Valid actuator position setpoints and ranges.

#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_OUT 17.8
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_OUT_MIN 17.5
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_OUT_MAX 18.5

#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_BOTTOM -3.5
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_BOTTOM_MIN -7.25
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_BOTTOM_MAX 0.25

#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_TOP -15.1
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_TOP_MIN -18.85
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_TOP_MAX -11.35

#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_OUT 19.15
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_OUT_MIN 18.5
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_OUT_MAX 19.5

#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_BOTTOM -3.5
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_BOTTOM_MIN -7.25
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_BOTTOM_MAX 0.25

#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_TOP -15.2
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_TOP_MIN -18.95
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_TOP_MAX -11.45

class CLSMAXvMotor;

class BioXASImagingCarbonFilterFarm : public BioXASCarbonFilterFarm
{
    Q_OBJECT

public:
	/// Constructor.
    explicit BioXASImagingCarbonFilterFarm(QObject *parent = 0);
	/// Destructor.
	virtual ~BioXASImagingCarbonFilterFarm();

	/// Returns the upstream actuator motor control.
	CLSMAXvMotor* upstreamMotor() const { return upstreamMotor_; }
	/// Return the downstream actuator motor control.
	CLSMAXvMotor* downstreamMotor() const { return downstreamMotor_; }

protected:
	/// The upstream actuator motor control.
	CLSMAXvMotor *upstreamMotor_;
	/// The downstream actuator motor control.
	CLSMAXvMotor *downstreamMotor_;
};

#endif // BIOXASIMAGINGCARBONFILTERFARM_H
