#ifndef BIOXASSIDECARBONFILTERFARM_H
#define BIOXASSIDECARBONFILTERFARM_H

#include "beamline/BioXAS/BioXASCarbonFilterFarm.h"

// Valid actuator position setpoints and ranges.

#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_OUT 18.96
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_OUT_MIN 18.91
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_OUT_MAX 19.01

#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_BOTTOM -3.5
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_BOTTOM_MIN -3.55
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_BOTTOM_MAX -3.45

#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_TOP -15.5
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_TOP_MIN -15.55
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_TOP_MAX -15.45

#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_OUT 19.16
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_OUT_MIN 19.11
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_OUT_MAX 19.21

#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_BOTTOM -3.5
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_BOTTOM_MIN -3.55
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_BOTTOM_MAX -3.45

#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_TOP -15.5
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_TOP_MIN -15.55
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_TOP_MAX -15.45

class BioXASSideCarbonFilterFarm : public BioXASCarbonFilterFarm
{
    Q_OBJECT

public:
	/// Constructor.
	explicit  BioXASSideCarbonFilterFarm(QObject *parent = 0);
	/// Destructor.
	virtual ~BioXASSideCarbonFilterFarm();
};

#endif // BIOXASSIDECARBONFILTERFARM_H
