#ifndef BIOXASSIDECARBONFILTERFARM_H
#define BIOXASSIDECARBONFILTERFARM_H

#include "beamline/BioXAS/BioXASCarbonFilterFarm.h"

// Valid actuator position setpoints and ranges.

#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_OUT 18.996
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_OUT_MIN 18.94
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_OUT_MAX 19.04

#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_BOTTOM -3.5
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_BOTTOM_MIN -3.55
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_BOTTOM_MAX -3.45

#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_TOP -15.1
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_TOP_MIN -15.15
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_TOP_MAX -15.05

#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_OUT 19.15
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_OUT_MIN 19.1
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_OUT_MAX 19.2

#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_BOTTOM -3.5
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_BOTTOM_MIN -3.55
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_BOTTOM_MAX -3.45

#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_TOP -15.2
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_TOP_MIN -15.25
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_TOP_MAX -15.15

class BioXASSideCarbonFilterFarm : public BioXASCarbonFilterFarm
{
    Q_OBJECT

public:
	/// Constructor.
	explicit  BioXASSideCarbonFilterFarm(QObject *parent = 0);
	/// Destructor.
	virtual ~BioXASSideCarbonFilterFarm();
};

#endif // BIOXASSIDECARBONFILTERFARM_H
