#ifndef BIOXASMAINCARBONFILTERFARM_H
#define BIOXASMAINCARBONFILTERFARM_H

#include "beamline/BioXAS/BioXASCarbonFilterFarm.h"

// Valid actuator positions.

#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_OUT 18.996
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_OUT_MIN 18.94
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_OUT_MAX 19.04

#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_BOTTOM -3.5
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_BOTTOM_MIN -3.55
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_BOTTOM_MAX -3.45

#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_TOP -15.1
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_TOP_MIN -15.15
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_TOP_MAX -15.05

#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_OUT 19.15
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_OUT_MIN 19.1
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_OUT_MAX 19.2

#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_BOTTOM -3.5
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_BOTTOM_MIN -3.55
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_BOTTOM_MAX -3.45

#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_TOP -15.2
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_TOP_MIN -15.25
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_TOP_MAX -15.15

class BioXASMainCarbonFilterFarm : public BioXASCarbonFilterFarm
{
    Q_OBJECT

public:
	/// Constructor.
    explicit BioXASMainCarbonFilterFarm(QObject *parent = 0);
	/// Destructor.
	virtual ~BioXASMainCarbonFilterFarm();
};

#endif // BIOXASMAINCARBONFILTERFARM_H
