#ifndef BIOXASIMAGINGCARBONFILTERFARM_H
#define BIOXASIMAGINGCARBONFILTERFARM_H

#include "beamline/BioXAS/BioXASCarbonFilterFarm.h"

// Valid actuator position setpoints and ranges.

#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_OUT 19.97
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_OUT_MIN 18
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_OUT_MAX 21

#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_BOTTOM -2.6
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_BOTTOM_MIN -4
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_BOTTOM_MAX -2

#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_TOP -14.65
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_TOP_MIN -16
#define BIOXASIMAGINGCARBONFILTERFARM_UPSTREAM_TOP_MAX -14

#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_OUT 21.0
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_OUT_MIN 20
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_OUT_MAX 22

#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_BOTTOM -2.5
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_BOTTOM_MIN -3.5
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_BOTTOM_MAX -1.5

#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_TOP -14.5
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_TOP_MIN -15.5
#define BIOXASIMAGINGCARBONFILTERFARM_DOWNSTREAM_TOP_MAX -13.5

class CLSMAXvMotor;

class BioXASImagingCarbonFilterFarm : public BioXASCarbonFilterFarm
{
    Q_OBJECT

public:
	/// Constructor.
    explicit BioXASImagingCarbonFilterFarm(QObject *parent = 0);
	/// Destructor.
	virtual ~BioXASImagingCarbonFilterFarm();

	/// Returns the upstream actuator motor control.
	CLSMAXvMotor* upstreamMotor() const { return upstreamMotor_; }
	/// Return the downstream actuator motor control.
	CLSMAXvMotor* downstreamMotor() const { return downstreamMotor_; }

protected:
	/// The upstream actuator motor control.
	CLSMAXvMotor *upstreamMotor_;
	/// The downstream actuator motor control.
	CLSMAXvMotor *downstreamMotor_;
};

#endif // BIOXASIMAGINGCARBONFILTERFARM_H
