#ifndef BIOXASMAINCARBONFILTERFARM_H
#define BIOXASMAINCARBONFILTERFARM_H

#include "beamline/BioXAS/BioXASCarbonFilterFarm.h"

// Valid actuator positions.

#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_OUT 19.8
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_OUT_MIN 19.75
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_OUT_MAX 19.85

#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_BOTTOM -3.5
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_BOTTOM_MIN -3.55
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_BOTTOM_MAX -3.45

#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_TOP -15.5
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_TOP_MIN -15.55
#define BIOXASMAINCARBONFILTERFARM_UPSTREAM_TOP_MAX -15.45

#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_OUT 19.06
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_OUT_MIN 19.01
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_OUT_MAX 19.11

#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_BOTTOM -3.5
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_BOTTOM_MIN -3.55
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_BOTTOM_MAX -3.45

#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_TOP -15.47
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_TOP_MIN -15.52
#define BIOXASMAINCARBONFILTERFARM_DOWNSTREAM_TOP_MAX -15.42

class BioXASMainCarbonFilterFarm : public BioXASCarbonFilterFarm
{
    Q_OBJECT

public:
	/// Constructor.
    explicit BioXASMainCarbonFilterFarm(QObject *parent = 0);
	/// Destructor.
	virtual ~BioXASMainCarbonFilterFarm();
};

#endif // BIOXASMAINCARBONFILTERFARM_H
