#ifndef BIOXASSIDECARBONFILTERFARM_H
#define BIOXASSIDECARBONFILTERFARM_H

#include "beamline/BioXAS/BioXASCarbonFilterFarm.h"

// Valid actuator position setpoints and ranges.

#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_OUT 17.9
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_OUT_MIN 17.5
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_OUT_MAX 18.5

#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_BOTTOM -3.5
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_BOTTOM_MIN -7.25
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_BOTTOM_MAX 0.25

#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_TOP -15.1
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_TOP_MIN -18.85
#define BIOXASSIDECARBONFILTERFARM_UPSTREAM_TOP_MAX -11.35

#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_OUT 19.15
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_OUT_MIN 18.5
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_OUT_MAX 19.5

#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_BOTTOM -3.5
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_BOTTOM_MIN -7.25
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_BOTTOM_MAX 0.25

#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_TOP -15.2
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_TOP_MIN -18.95
#define BIOXASSIDECARBONFILTERFARM_DOWNSTREAM_TOP_MAX -11.45

class BioXASSideCarbonFilterFarm : public BioXASCarbonFilterFarm
{
    Q_OBJECT

public:
	/// Constructor.
	explicit  BioXASSideCarbonFilterFarm(QObject *parent = 0);
	/// Destructor.
	virtual ~BioXASSideCarbonFilterFarm();
};

#endif // BIOXASSIDECARBONFILTERFARM_H
