#ifndef SGMXASLADDER_H
#define SGMXASLADDER_H

#include "beamline/SGM/SGMLadderControl.h"

#define SGMXASLADDER_VANADIUM_SETPOINT 0
#define SGMXASLADDER_VANADIUM_MIN 0
#define SGMXASLADDER_VANADIUM_MAX 0

#define SGMXASLADDER_PHOTODIODE_SETPOINT 1700
#define SGMXASLADDER_PHOTODIODE_MIN 0
#define SGMXASLADDER_PHOTODIODE_MAX 3400

#define SGMXASLADDER_MESH_SETPOINT 21000
#define SGMXASLADDER_MESH_MIN 18000
#define SGMXASLADDER_MESH_MAX 24000

#define SGMXASLADDER_PINHOLE_SETPOINT 21000
#define SGMXASLADDER_PINHOLE_MIN 18000
#define SGMXASLADDER_PINHOLE_MAX 24000

#define SGMXASLADDER_PASSTHROUGH_SETPOINT 26000
#define SGMXASLADDER_PASSTHROUGH_MIN 26000
#define SGMXASLADDER_PASSTHROUGH_MAX 26000

#define SGMXASLADDER_PHOSPHOR_SETPOINT 26000
#define SGMXASLADDER_PHOSPHOR_MIN 26000
#define SGMXASLADDER_PHOSPHOR_MAX 26000

class SGMXASLadder : public SGMLadderControl
{
	Q_OBJECT

public:
	/// Enum defining the different value options.
	enum Option { Vanadium = 0, Photodiode = 1, AuMesh = 2, Pinhole = 3, Passthrough = 4, Phosphor = 5 };

	/// Constructor.
	explicit SGMXASLadder(const QString &name, const QString &baseName, QObject *parent = 0);
	/// Destructor.
	virtual ~SGMXASLadder();
};

#endif // SGMXASLADDER_H
