#ifndef SXRMBFOURELEMENTVORTEXDETECTOR_H
#define SXRMBFOURELEMENTVORTEXDETECTOR_H

class SXRMBFourElementVortexDetector
{
public:
    SXRMBFourElementVortexDetector();
};

#endif // SXRMBFOURELEMENTVORTEXDETECTOR_H
