#ifndef AMGENERICSTEPSCANCONFIGURATIONVIEW_H
#define AMGENERICSTEPSCANCONFIGURATIONVIEW_H

class AMGenericStepScanConfigurationView
{
public:
    AMGenericStepScanConfigurationView();
};

#endif // AMGENERICSTEPSCANCONFIGURATIONVIEW_H
