#ifndef AMTIMEDSCANACTIONCONTROLLERASSEMBLER_H
#define AMTIMEDSCANACTIONCONTROLLERASSEMBLER_H

class AMTimedScanActionControllerAssembler
{
public:
    AMTimedScanActionControllerAssembler();
};

#endif // AMTIMEDSCANACTIONCONTROLLERASSEMBLER_H
