#ifndef VESPERSTIMEDLINESCANCONFIGURATIONVIEW_H
#define VESPERSTIMEDLINESCANCONFIGURATIONVIEW_H

class VESPERSTimedLineScanConfigurationView
{
public:
    VESPERSTimedLineScanConfigurationView();
};

#endif // VESPERSTIMEDLINESCANCONFIGURATIONVIEW_H
