#ifndef VESPERS2DSCANCONFIGURATIONVIEW_H
#define VESPERS2DSCANCONFIGURATIONVIEW_H

class VESPERS2DScanConfigurationView
{
public:
    VESPERS2DScanConfigurationView();
};

#endif // VESPERS2DSCANCONFIGURATIONVIEW_H
