#ifndef VESPERS3DSCANCONFIGURATIONVIEW_H
#define VESPERS3DSCANCONFIGURATIONVIEW_H

class VESPERS3DScanConfigurationView
{
public:
    VESPERS3DScanConfigurationView();
};

#endif // VESPERS3DSCANCONFIGURATIONVIEW_H
