#!/bin/bash -x
# Adjust the target directory to reflect the date
# After rolling on the symbolic link in the ioc_app_dir will need to be adjusted to point at the correct installation

ioc_app_dir=/home/IOC2026-001
target_dir=beamline/acquaman/CLSSR570Coordinator

#
# Test and make directories
#
if [[ ! -d $ioc_app_dir ]]
then
	echo "/ioc_app is NOT Mounted!"
	exit
fi

if [[ ! -d $ioc_app_dir/$target_dir ]]
then
	mkdir $ioc_app_dir/$target_dir
fi

# Install files
cp ./clsSR570Coordinator $ioc_app_dir/$target_dir
cp ./runCLSSR570CoordinatorStartup $ioc_app_dir/$target_dir
cp ../../../build/CLSSR570Coordinator $ioc_app_dir/$target_dir

