#ifndef IDEASSCANCONFIGURATIONDBOBJECT_H
#define IDEASSCANCONFIGURATIONDBOBJECT_H

class IDEASScanConfigurationDbObject
{
public:
    IDEASScanConfigurationDbObject();
};

#endif // IDEASSCANCONFIGURATIONDBOBJECT_H
