#ifndef VESPERSTIMEDLINESCANCONFIGURATION_H
#define VESPERSTIMEDLINESCANCONFIGURATION_H

class VESPERSTimedLineScanConfiguration
{
public:
    VESPERSTimedLineScanConfiguration();
};

#endif // VESPERSTIMEDLINESCANCONFIGURATION_H
