#ifndef VESPERS3DDACQSCANCONTROLLER_H
#define VESPERS3DDACQSCANCONTROLLER_H

class VESPERS3DDacqScanController
{
public:
    VESPERS3DDacqScanController();
};

#endif // VESPERS3DDACQSCANCONTROLLER_H
