#ifndef VESPERSTIMEDLINESCANACTIONCONTROLLER_H
#define VESPERSTIMEDLINESCANACTIONCONTROLLER_H

class VESPERSTimedLineScanActionController
{
public:
    VESPERSTimedLineScanActionController();
};

#endif // VESPERSTIMEDLINESCANACTIONCONTROLLER_H
