#ifndef AMDIRECTORYSYNCHRONIZER_H
#define AMDIRECTORYSYNCHRONIZER_H

#include <QObject>
#include <QProcess>
#include "AMRecursiveDirectoryCompare.h"
/**
 * @brief Class designed to recursively synchronize the data in two folders, while
 * checking the validity of the states of both directories before proceeding
 */
class AMDirectorySynchronizer : public QObject
{
	Q_OBJECT
private:
	/// @brief The directory to copy to
	QString destinationDirectory_;
	/// @brief The directory to copy from
	QString sourceDirectory_;
	/// @brief A short description of the last message generated by the AMDirectorySynchronizer
	QString lastMessage_;
	/// @brief A process which actually performs the copy
	QProcess copyProcess_;
public:
	/**
	 * @brief Creates an instance of an AMDirectorySynchronizer with the provided sourceDirectory
	 * and destinationDirectory
	 * @param sourceDirectory::QString ~ The path of the directory to copy data from
	 * @param destinationDirectory::QString ~ The path of the directory to copy data to
	 */
	explicit AMDirectorySynchronizer(const QString& sourceDirectory, const QString& destinationDirectory, QObject *parent = 0);
	/// @brief Simple validation of path. Ensures it exists, and is a folder, not a file
	bool validatePath(const QString& path);
	/// @brief Starts the process of copying the files from the source to the destination
	bool start();


protected:
	/// @brief Checks to see if any files exist in the source but not the directory, or
	/// vice versa, or both
	AMRecursiveDirectoryCompare::DirectoryCompareResult compareDirectories();

	/// @brief Sets a message associated with the AMDirectorySynchronizer
	void setLastMessage(const QString& message);

signals:
	/// @brief Signal emitted when the copy is completed successfully
	copyCompleted();
	/// @brief Signal emitted when the copy terminates unexpectedly after starting
	copyError();
	/// @brief Signal emitted whenever the Last Message changes
	lastMessageChanged(const QString& value);
protected slots:
	/// @brief Handles the process having Standard Error output to read (places it in lastMessage_)
	void onCopyReadyReadStdErr();
	/// @brief Handles the copy process exiting
	void onCopyFinished(int, QProcess::ExitStatus);
public slots:
	
};

#endif // AMDIRECTORYSYNCHRONIZER_H
